create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  author_name text not null check (char_length(trim(author_name)) > 0),
  comment text not null check (char_length(trim(comment)) > 0),
  rating numeric(2,1) not null check (rating >= 0.5 and rating <= 5.0)
);

alter table public.reviews enable row level security;

create policy "public can read reviews"
on public.reviews
for select
to public
using (true);

create policy "public can insert reviews"
on public.reviews
for insert
to public
with check (true);
